version: '3'

networks:
  iroha-network:
    name: iroha-network

services:
  client:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    command:
      - /usr/local/bin/poetry
      - run
      - strawberry
      - server
      - playground.app
    tty: true
    depends_on:
      - node
    networks:
      - iroha-network

  node:
    image: hyperledger/iroha:latest
    ports:
      # -  "${IROHA_PORT}:50051"
      # -  "${IROHA_TLS_PORT}:55552"
      # -  "${DEBUGGER_PORT}:20000"
      -  "50051:50051"
      -  "55552:55552"
      -  "20000:20000"
    environment:
      - KEY=node
      - IROHA_POSTGRES_HOST=postgres
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
      - CCACHE_DIR=/tmp/ccache
    # export G_ID=$(id -g $(whoami))
    # export U_ID=$(id -g $(whoami))
    user: ${U_ID:-0}:${G_ID:-0}
    depends_on:
      - postgres
    # tty: true
    volumes:
      - ./iroha:/opt/iroha:delegated
      - ccache-data:/tmp/ccache:delegated
      - blockstore:/opt/iroha_data/blocks:delegated
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    networks:
      - iroha-network

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=helloworld
    command: -c 'max_prepared_transactions=100'
    networks:
      - iroha-network

volumes:
  ccache-data:
    name: ccache-data
  blockstore:
      name: blockstore
